services:
  mysql:
    container_name: mysql-server
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
      DATABASE_NAME: $DATABASE_NAME
    volumes:
      - ./:/proyecto_sql
    ports:
      - "3306:3306"

      