


services: 
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=coderhouse
    ports:
      - '3333:3306'
    volumes:
      - ./:/proyecto_sql